apiVersion: v1
kind: Namespace
metadata:
  name: hadoop

---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: hadoop
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: namenode

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: hadoop
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    app: spark-master

---
apiVersion: v1
kind: Service
metadata:
  name: hdfs
  namespace: hadoop
spec:
  type: LoadBalancer
  ports:
    - port: 9870
      targetPort: 9870
  selector:
    app: namenode

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  namespace: hadoop
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spark-master

---
apiVersion: v1
kind: Service
metadata:
  name: spark-history
  namespace: hadoop
spec:
  type: LoadBalancer
  ports:
    - port: 18080
      targetPort: 18080
  selector:
    app: spark-history
